"""Assignment rule schemas for API validation."""

from datetime import datetime
from typing import Optional, List

from pydantic import BaseModel, Field


class AssignmentRuleBase(BaseModel):
    """Base assignment rule schema."""

    name: str = Field(..., max_length=200)
    description: Optional[str] = None
    keywords: Optional[str] = Field(
        None,
        description="Comma-separated keywords to match in transaction label/reference/note"
    )
    counterparty: Optional[str] = Field(
        None,
        max_length=200,
        description="Exact counterparty name to match"
    )
    counterparty_pattern: Optional[str] = Field(
        None,
        max_length=200,
        description="Pattern for counterparty (supports * wildcards)"
    )
    client_name_suggested: Optional[str] = Field(
        None,
        max_length=200,
        description="Client name to suggest when rule matches"
    )
    project_id_suggested: Optional[int] = Field(
        None,
        description="Project ID to suggest when rule matches"
    )
    priority: int = Field(
        default=0,
        description="Rule priority (higher = evaluated first)"
    )
    is_active: bool = True


class AssignmentRuleCreate(AssignmentRuleBase):
    """Schema for creating an assignment rule."""
    pass


class AssignmentRuleUpdate(BaseModel):
    """Schema for updating an assignment rule."""

    name: Optional[str] = Field(None, max_length=200)
    description: Optional[str] = None
    keywords: Optional[str] = None
    counterparty: Optional[str] = None
    counterparty_pattern: Optional[str] = None
    client_name_suggested: Optional[str] = None
    project_id_suggested: Optional[int] = None
    priority: Optional[int] = None
    is_active: Optional[bool] = None


class AssignmentRuleResponse(AssignmentRuleBase):
    """Schema for assignment rule response."""

    id: int
    project_name: Optional[str] = None
    project_code: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class AssignmentRuleListResponse(BaseModel):
    """Schema for paginated rule list."""

    items: List[AssignmentRuleResponse]
    total: int


class RuleSuggestion(BaseModel):
    """Suggestion generated by a rule."""

    rule_id: int
    rule_name: str
    project_id: Optional[int] = None
    project_name: Optional[str] = None
    project_code: Optional[str] = None
    client_name: Optional[str] = None
    reason: str = Field(
        ...,
        description="Explanation of why this rule matched"
    )
    priority: int


class TransactionRuleSuggestion(BaseModel):
    """Rule suggestion for a transaction."""

    transaction_id: int
    suggestions: List[RuleSuggestion]
